### ISSUE TITLE
step_embed throws Error: "Error in if (is.na(b)) return(1L) : argument is of length zero"

### ISSUE THREAD

**Issue by agilebean** [tidymodels/embed#47] opened 2020-06-26 15:49 UTC
A fix is needed because of library `tensorflow`.

Using 
```
embed_0.1.0 
tensorflow_2.2.0
reticulate_1.16
tidyverse_1.3.0
```

`prep.encoding <- prep(recipe.encoding, training = training.set, retain = TRUE)`

throws Error:
`Error in if (is.na(b)) return(1L) : argument is of length zero`

from this line:
`compareVersion("2.0", as.character(tensorflow::tf_version()))`

because
`tensorflow::tf_version()` returns `NULL`

**Comment by topepo** [comment] 2020-06-26 18:43
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

Right now the best way to install reprex is:
```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

**Comment by topepo** [comment] 2020-06-27 19:07
This would be better fixed by putting an issue into the `tensorflow` project.

**Closed by topepo** 2020-06-27 19:07 UTC
Labels: reprex

**Comment by agilebean** [comment] 2020-06-29 11:54
Please reopen, because this issue prevents to use the keras embedding.
I actually provided a reprex already in the issue description:
`compareVersion("2.0", as.character(tensorflow::tf_version()))`
throws the error described.
This line must be fixed, rather than waiting for a potential fix in tensorflow somewhere in the future...

**Comment by topepo** [comment] 2020-06-29 13:53
If the underlying issue isn't fixed, there will be multiple band-aids in different places to deal with the problem that can only be fixed by `tensorflow`. That's why it is important for you to give them a reproducible example so that this can be solved the right way.

**Comment by topepo** [comment] 2020-06-29 18:26
It looks like it happens on the first invokation. Until they fix it, run `tensorflow::tf_version()` before running `prep()` and you should be fine until they fix it. 

```r
Restarting R session...

> tensorflow::tf_version()
NULL
> tensorflow::tf_version()
[1] ‘2.2’
```

**Comment by topepo** [comment] 2020-06-29 18:36
rstudio/tensorflow#426

**Comment by dfalbel** [comment] 2020-07-03 13:45
FYI this should be fixed in dev reticulate. You can test with:

```
remotes::install_github("rstudio/reticulate")
```

**Comment by agilebean** [comment] 2020-07-06 09:43
> It looks like it happens on the first invokation. Until they fix it, run `tensorflow::tf_version()` before running `prep()` and you should be fine until they fix it.

thanks, this worked indeed.
